# Default values for errbit.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
revisionHistoryLimit: 2
replicaCount: 1
image:
  repository: tmaier/errbit-helm
  tag: latest
  pullPolicy: Always
service:
  name: http
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
ingress:
  enabled: false
  path: '/*'
  # Used to create an Ingress record.
  hosts:
    - errbit.example.local
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: errbit-example-tls
    #   hosts:
    #     - errbit.example.local
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 50m
  #  memory: 500Mi
  # requests:
  #  cpu: 20m
  #  memory: 50Mi
batch:
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 10m
    #  memory: 1024Mi
    # requests:
    #  cpu: 50m
    #  memory: 512Mi

## Configure access to an external database
## For these settings to be used you need to disable
## the included postgresql database below
# mongodbHost:
# mongodbPort: 27017
# mongodbPassword:
# mongodbUsername:
# mongodbDatabase: errbit

## Configure Errbit
## See https://github.com/errbit/errbit/blob/master/docs/configuration.md for the available environment variables
## You can store them in config and configSecure. The difference is that the one uses a ConfigMap, the other a Secret
config:
  ERRBIT_ADMIN_EMAIL: errbit@example.com
  ERRBIT_ADMIN_USER: errbit
  ERRBIT_EMAIL_FROM: "errbit.noreply@example.com"
  ERRBIT_ENFORCE_SSL: "false"
  ERRBIT_HOST: "errbit.example.local"
  ERRBIT_PORT: "80"
  ERRBIT_PROTOCOL: http
  ERRBIT_USE_GRAVATAR: "true"
  PORT: '8080'
  RACK_ENV: deployment
  RAILS_ENV: production
configSecure:
  ERRBIT_ADMIN_PASSWORD: password
  SECRET_KEY_BASE: "please change me"

## Sets whether the database shall be setup when
## the helm chart gets installed
bootstrapErrbit: true

networkPolicy:
  ## Enable creation of NetworkPolicy resources.
  ##
  enabled: false
## Configuration values for the mongodb dependency.
## ref: https://github.com/kubernetes/charts/blob/master/stable/mongodb/README.md
##
mongodb:
  enabled: true
  mongodbUsername: errbit
  mongodbPassword: errbit
  mongodbDatabase: errbit
  persistence:
    ## Consider to reduce the allocated disk space to fit the need
    # size: 8Gi
