apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "errbit-helm.fullname" . }}
  labels:
    app: {{ template "errbit-helm.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "errbit-helm.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/cm.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          env:
            - name: MONGODB_USERNAME
              value: {{ template "errbit-helm.mongodbUsername" . }}
            {{- if .Values.mongodb.enabled }}
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "mongodb.fullname" . }}
                  key: mongodb-password
            {{- end }}
            - name: MONGODB_HOST
              value: {{ template "errbit-helm.mongodbHost" . }}
            - name: MONGODB_PORT
              value: {{ template "errbit-helm.mongodbPort" . }}
            - name: MONGODB_DATABASE
              value: {{ template "errbit-helm.mongodbDatabase" . }}
          envFrom:
            - secretRef:
                name: {{ template "errbit-helm.fullname" . }}
            - configMapRef:
                name: {{ template "errbit-helm.fullname" . }}
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 60
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: {{ .Values.service.internalPort }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
